public class Main {

    public static void main(String[] args) {
        
        System.out.println("MY NAME IS ADARSH DUBEY AND I BUILD MY FIRST DOCKER FILE BY USING THE CODE OF JAVA ");
        System.out.print("THERE ARE SEVERAL STEPS TO WRITE THE DOCKERFILE \n STEP-1: WRITE THE BASE IMAGE \n STEP-2: CREATION OF WORKING FOLDER \n STEP-3: COPY SOURCE CODE OF THE HOST MACHINE TO THE CONTAINER \n STEP-4: COMPILE THE APPLICATION CODE BY USING THE RUN COMMAND ");
    }
}